In [138]:
import numpy as np
import pandas as pd

In [139]:
test = pd.read_csv("teste.csv", header = None)
train = pd.read_csv("treinamento.csv", header = None)

In [140]:
train

0       1       2    3
0   1.4715  0.8996  1.1509  0.0
1   4.6315  0.3409  2.4209  0.0
2   2.9055  3.1858  3.1770  1.0
3   3.2563  4.3231  3.8009  1.0
4   0.2798  4.0843  2.2521  1.0
5   2.6446  3.4718  3.2715  1.0
6   1.0620  2.7164  1.7854  0.0
7   3.5126  4.7822  4.1947  1.0
8   2.2227  0.4270  1.2697  0.0
9   0.2867  3.1473  1.8032  1.0
10  3.9809  3.4560  3.5633  0.0
11  1.7265  4.7341  3.2849  1.0
12  2.6010  4.7691  3.5963  0.0
13  0.3680  1.0352  0.6746  0.0
14  3.8751  4.5709  4.2678  1.0
15  3.9128  1.4777  2.8539  1.0
16  0.7592  4.2396  2.4817  0.0
17  3.9243  1.3542  2.6833  1.0
18  1.1391  1.6051  1.4366  1.0
19  4.1478  4.1109  3.9658  0.0
20  2.8534  2.8591  2.6066  0.0
21  1.4301  3.4957  2.3753  0.0
22  3.9813  2.2079  3.1615  1.0
23  2.2311  2.3283  2.2591  0.0
24  1.3952  3.3769  2.5501  1.0
25  4.5183  4.5426  4.4525  0.0
26  3.7360  1.3026  2.4848  0.0
27  3.4482  0.6592  2.1827  1.0
28  0.6175  0.9545  0.8701  1.0
29  0.7287  2.9252  1.7742  0.0

In [141]:
test

0       1       2    3
0  4.0736  4.5290  4.2580  0.0
1  0.6349  4.5669  2.4343  0.0
2  3.1618  0.4877  1.8373  0.0
3  1.3925  2.7344  2.0922  1.0
4  4.7875  4.8244  4.6913  0.0
5  0.7881  4.8530  2.9396  1.0
6  4.7858  2.4269  3.7253  1.0
7  4.0014  0.7094  2.3517  0.0
8  2.1088  4.5787  3.3765  1.0
9  3.9610  4.7975  4.3967  1.0

In [142]:
Namostras = len(train)
Mamostras = len(test)

In [143]:
Namostras

30

In [144]:
Mamostras

10

In [145]:
w = []
for i in range(4):
    w.append(np.random.rand())

In [146]:
n = 0.01

In [147]:
X = train.loc[:,0:2]
D = train.loc[:,3]

In [148]:
X_test = test.loc[:,0:2]
D_test = test.loc[:,3]

In [149]:
X[3] = -1

In [150]:
X_test[3] = -1

In [151]:
X = np.array(X)

In [152]:
X_test = np.array(X_test)

In [153]:
X

array([[ 1.4715,  0.8996,  1.1509, -1.    ],
       [ 4.6315,  0.3409,  2.4209, -1.    ],
       [ 2.9055,  3.1858,  3.177 , -1.    ],
       [ 3.2563,  4.3231,  3.8009, -1.    ],
       [ 0.2798,  4.0843,  2.2521, -1.    ],
       [ 2.6446,  3.4718,  3.2715, -1.    ],
       [ 1.062 ,  2.7164,  1.7854, -1.    ],
       [ 3.5126,  4.7822,  4.1947, -1.    ],
       [ 2.2227,  0.427 ,  1.2697, -1.    ],
       [ 0.2867,  3.1473,  1.8032, -1.    ],
       [ 3.9809,  3.456 ,  3.5633, -1.    ],
       [ 1.7265,  4.7341,  3.2849, -1.    ],
       [ 2.601 ,  4.7691,  3.5963, -1.    ],
       [ 0.368 ,  1.0352,  0.6746, -1.    ],
       [ 3.8751,  4.5709,  4.2678, -1.    ],
       [ 3.9128,  1.4777,  2.8539, -1.    ],
       [ 0.7592,  4.2396,  2.4817, -1.    ],
       [ 3.9243,  1.3542,  2.6833, -1.    ],
       [ 1.1391,  1.6051,  1.4366, -1.    ],
       [ 4.1478,  4.1109,  3.9658, -1.    ],
       [ 2.8534,  2.8591,  2.6066, -1.    ],
       [ 1.4301,  3.4957,  2.3753, -1.    ],
       [ 3

In [154]:
X_test

array([[ 4.0736,  4.529 ,  4.258 , -1.    ],
       [ 0.6349,  4.5669,  2.4343, -1.    ],
       [ 3.1618,  0.4877,  1.8373, -1.    ],
       [ 1.3925,  2.7344,  2.0922, -1.    ],
       [ 4.7875,  4.8244,  4.6913, -1.    ],
       [ 0.7881,  4.853 ,  2.9396, -1.    ],
       [ 4.7858,  2.4269,  3.7253, -1.    ],
       [ 4.0014,  0.7094,  2.3517, -1.    ],
       [ 2.1088,  4.5787,  3.3765, -1.    ],
       [ 3.961 ,  4.7975,  4.3967, -1.    ]])

In [155]:
D

0     0.0
1     0.0
2     1.0
3     1.0
4     1.0
5     1.0
6     0.0
7     1.0
8     0.0
9     1.0
10    0.0
11    1.0
12    0.0
13    0.0
14    1.0
15    1.0
16    0.0
17    1.0
18    1.0
19    0.0
20    0.0
21    0.0
22    1.0
23    0.0
24    1.0
25    0.0
26    0.0
27    1.0
28    1.0
29    0.0
Name: 3, dtype: float64

In [156]:
w

[0.20242826327211394,
 0.19499950428179735,
 0.6547054534190304,
 0.6196204808907594]

In [157]:
X[0]

array([ 1.4715,  0.8996,  1.1509, -1.    ])

In [158]:
X


array([[ 1.4715,  0.8996,  1.1509, -1.    ],
       [ 4.6315,  0.3409,  2.4209, -1.    ],
       [ 2.9055,  3.1858,  3.177 , -1.    ],
       [ 3.2563,  4.3231,  3.8009, -1.    ],
       [ 0.2798,  4.0843,  2.2521, -1.    ],
       [ 2.6446,  3.4718,  3.2715, -1.    ],
       [ 1.062 ,  2.7164,  1.7854, -1.    ],
       [ 3.5126,  4.7822,  4.1947, -1.    ],
       [ 2.2227,  0.427 ,  1.2697, -1.    ],
       [ 0.2867,  3.1473,  1.8032, -1.    ],
       [ 3.9809,  3.456 ,  3.5633, -1.    ],
       [ 1.7265,  4.7341,  3.2849, -1.    ],
       [ 2.601 ,  4.7691,  3.5963, -1.    ],
       [ 0.368 ,  1.0352,  0.6746, -1.    ],
       [ 3.8751,  4.5709,  4.2678, -1.    ],
       [ 3.9128,  1.4777,  2.8539, -1.    ],
       [ 0.7592,  4.2396,  2.4817, -1.    ],
       [ 3.9243,  1.3542,  2.6833, -1.    ],
       [ 1.1391,  1.6051,  1.4366, -1.    ],
       [ 4.1478,  4.1109,  3.9658, -1.    ],
       [ 2.8534,  2.8591,  2.6066, -1.    ],
       [ 1.4301,  3.4957,  2.3753, -1.    ],
       [ 3

In [159]:
error = 1
y = np.zeros(Namostras)
while(error):
    error = 0
    for k in range(Namostras):
        u = np.dot(w,X[k])
        if u >= 0:
            y[k] = 1
        else:
            y[k] = 0

            if int(y[k]) != int(D[k]):
                w = w + n*(D[k]-y[k])*X[k]
                error = 1

In [160]:
w

[0.20242826327211394,
 0.19499950428179735,
 0.6547054534190304,
 0.6196204808907594]

In [161]:
Namostras_test = len(test)


In [162]:

certains = 0
errors = 0
y_test = np.zeros(Namostras_test)
for k in range(Namostras_test):
    u = np.dot(w, X_test[k])
    if u >= 0:
        y_test[k] = 1
    else:
        y_test[k] = 0
    if y_test[k] == D_test[k]:
            certains = certains + 1
    else:
            errors = errors + 1

In [163]:
print("Hits" + str(certains))
print("Errors" + str(errors))

Hits5
Errors5
